spring:

    mvc:
      throw-exception-if-no-handler-found: true
    resources:
      add-mapping: false
    jpa:
      database: POSTGRESQL
      show-sql: true
      hibernate:
        ddl-auto: create-drop

    datasource:
      platform: postgres
      url: jdbc:postgresql://localhost:5432/todo
      username: postgres
      password: mindig
      driverClassName: org.postgresql.Driver

    logging:
      level:
        org:
          springframework:
            security: DEBUG

cors:
  allowed-origins: "http://localhost:4200"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true